<#
.SYNOPSIS
    Generates ServerFiles.wxs from current autocad-mcp-server build output.

.DESCRIPTION
    Scans autocad-mcp-server/build/ and generates WiX component entries.
    Maps build subdirectories to the Directory IDs defined in Product.wxs:
        build/          → DIR_Server_build
        build/tools/    → DIR_Server_tools
        build/utils/    → DIR_Server_utils

    Run this after 'npm run build' in autocad-mcp-server.

.EXAMPLE
    .\Generate-ServerFiles.ps1
    .\Generate-ServerFiles.ps1 -ServerBuildDir "E:\path\to\autocad-mcp-server\build"
#>
param(
    [string]$ServerBuildDir = (Resolve-Path "$PSScriptRoot\..\..\..\..\autocad-mcp-server\build").Path,
    [string]$OutputFile     = "$PSScriptRoot\ServerFiles.wxs"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Map each subdirectory path (relative to build/) to its WiX Directory ID
$dirIdMap = @{
    ""       = "DIR_Server_build"
    "tools"  = "DIR_Server_tools"
    "utils"  = "DIR_Server_utils"
}

function Sanitize-Id([string]$name) {
    # WiX component IDs must be alphanumeric + underscores
    $name -replace '[^a-zA-Z0-9]', '_'
}

Write-Host "Scanning: $ServerBuildDir"

$files = Get-ChildItem -Path $ServerBuildDir -Recurse -File | Sort-Object FullName

$components = [System.Collections.Generic.List[string]]::new()

foreach ($file in $files) {
    $relPath   = $file.FullName.Substring($ServerBuildDir.Length).TrimStart('\', '/')
    $relDir    = [System.IO.Path]::GetDirectoryName($relPath).Replace('/', '\')
    $relDir    = if ($relDir) { $relDir.TrimStart('\') } else { "" }

    # Check if directory is mapped; skip files in unmapped subdirs
    if (-not $dirIdMap.ContainsKey($relDir)) {
        Write-Warning "Skipping unmapped directory: $relDir (file: $relPath)"
        Write-Warning "  → Add '$relDir' to dirIdMap and a <Directory> entry in Product.wxs"
        continue
    }

    $dirId      = $dirIdMap[$relDir]
    $safeId     = "SrvComp_" + (Sanitize-Id $relPath)
    $wixSource  = '$(var.ServerBuildDir)\' + $relPath

    $components.Add(@"
      <Component Id="$safeId" Directory="$dirId" Guid="*">
        <File Source="$wixSource" KeyPath="yes" />
      </Component>
"@)
}

Write-Host "  Found $($components.Count) files"

$xml = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by Generate-ServerFiles.ps1 — DO NOT EDIT MANUALLY -->
<!-- Re-run .\Generate-ServerFiles.ps1 (or .\Build-Installer.ps1) when server/build content changes -->

<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="ServerBuildFiles">
$($components -join "`n")
    </ComponentGroup>
  </Fragment>
</Wix>
"@

Set-Content -Path $OutputFile -Value $xml -Encoding UTF8
Write-Host "Written: $OutputFile"
