<#
.SYNOPSIS
    Generates ServerNodeModules.wxs from autocad-mcp-server/node_modules (production deps).

.DESCRIPTION
    Traverses the node_modules directory and creates:
      1. Nested <DirectoryRef> / <Directory> declarations for every subdirectory
      2. <ComponentGroup Id="ServerNodeModulesFiles"> with one Component per file

    Run this after 'npm prune --production' in autocad-mcp-server (or the
    Build-Installer.ps1 script handles that automatically).

    ⚠  node_modules can contain thousands of files. Expect the generated .wxs to be large.

.EXAMPLE
    .\Generate-ServerNodeModules.ps1
    .\Generate-ServerNodeModules.ps1 -NodeModulesDir "E:\path\to\autocad-mcp-server\node_modules"
#>
param(
    [string]$NodeModulesDir = (Resolve-Path "$PSScriptRoot\..\..\..\..\autocad-mcp-server\node_modules").Path,
    [string]$OutputFile     = "$PSScriptRoot\ServerNodeModules.wxs"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "Scanning node_modules: $NodeModulesDir"

# ── Collect all directories and files ────────────────────────────────────────

$allDirs  = Get-ChildItem -Path $NodeModulesDir -Recurse -Directory | Sort-Object FullName
$allFiles = Get-ChildItem -Path $NodeModulesDir -Recurse -File      | Sort-Object FullName

Write-Host "  Directories : $($allDirs.Count)"
Write-Host "  Files       : $($allFiles.Count)"

# ── Build directory ID map ───────────────────────────────────────────────────
# Root node_modules itself is declared in Product.wxs as DIR_Server_node_modules
# Each subdirectory gets a generated ID: DIR_SNM_{counter}

$dirIdMap = @{ $NodeModulesDir = "DIR_Server_node_modules" }
$counter  = 0

foreach ($dir in $allDirs) {
    $counter++
    $dirIdMap[$dir.FullName] = "DIR_SNM_{0:D7}" -f $counter
}

# ── Helper ───────────────────────────────────────────────────────────────────
function Sanitize-Id([string]$s) {
    ($s -replace '[^a-zA-Z0-9_]', '_').TrimStart('_')
}

# ── Build XML ────────────────────────────────────────────────────────────────
$sb_dirs       = [System.Text.StringBuilder]::new()
$sb_components = [System.Text.StringBuilder]::new()

# Directory declarations — group by parent
# We output a flat list of DirectoryRef entries to keep it manageable
[void]$sb_dirs.AppendLine('  <Fragment>')
[void]$sb_dirs.AppendLine('    <DirectoryRef Id="DIR_Server_node_modules">')

# Recursive directory builder (outputs nested <Directory> under DirectoryRef)
function Write-DirTree {
    param(
        [string]$parentPath,
        [int]$indent,
        [System.Collections.Hashtable]$idMap,
        [System.IO.DirectoryInfo[]]$allDirsArr,
        [System.Text.StringBuilder]$sb
    )

    $pad = "  " * $indent
    $children = $allDirsArr | Where-Object { $_.Parent.FullName -eq $parentPath }

    foreach ($child in $children) {
        $id = $idMap[$child.FullName]
        [void]$sb.AppendLine("$pad<Directory Id=""$id"" Name=""$($child.Name)"">")
        Write-DirTree -parentPath $child.FullName -indent ($indent + 1) -idMap $idMap -allDirsArr $allDirsArr -sb $sb
        [void]$sb.AppendLine("$pad</Directory>")
    }
}

Write-DirTree -parentPath $NodeModulesDir -indent 3 -idMap $dirIdMap -allDirsArr $allDirs -sb $sb_dirs

[void]$sb_dirs.AppendLine('    </DirectoryRef>')
[void]$sb_dirs.AppendLine('  </Fragment>')

# Component declarations
[void]$sb_components.AppendLine('  <Fragment>')
[void]$sb_components.AppendLine('    <ComponentGroup Id="ServerNodeModulesFiles">')

$fileCounter = 0
foreach ($file in $allFiles) {
    $fileCounter++
    $parentDir = $file.DirectoryName

    if (-not $dirIdMap.ContainsKey($parentDir)) {
        Write-Warning "Unmapped directory for file: $($file.FullName)"
        continue
    }

    $dirId      = $dirIdMap[$parentDir]
    $compId     = "SrvNm_f{0:D7}" -f $fileCounter
    $relPath    = $file.FullName.Substring($NodeModulesDir.Length).TrimStart('\', '/')
    $wixSource  = '$(var.ServerNodeModulesDir)\' + $relPath

    [void]$sb_components.AppendLine("      <Component Id=""$compId"" Directory=""$dirId"" Guid=""*"" Bitness=""always64"">")
    [void]$sb_components.AppendLine("        <File Source=""$wixSource"" KeyPath=""yes"" />")
    [void]$sb_components.AppendLine("      </Component>")
}

[void]$sb_components.AppendLine('    </ComponentGroup>')
[void]$sb_components.AppendLine('  </Fragment>')

# ── Write output ──────────────────────────────────────────────────────────────
$header = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by Generate-ServerNodeModules.ps1. Do not edit manually. -->
<!-- Re-run after pruning production dependencies in autocad-mcp-server. -->

<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
"@

$footer = "</Wix>"

$content = $header + "`n" + $sb_dirs.ToString() + "`n" + $sb_components.ToString() + "`n" + $footer
Set-Content -Path $OutputFile -Value $content -Encoding UTF8

Write-Host "Written: $OutputFile"
Write-Host "  Directories : $($dirIdMap.Count - 1)  (+ root)"
Write-Host "  Files       : $fileCounter"
